list_of_title = ['Axelle Red - Ce matin',
                 'Axelle Red - Ma prière',
                 'BENEE - Supalonely',
                 'Clara Luciani - Nue',
                 'Prince Karma - Later B***',
                 '2Pac&Biggie - Redbone',
                 '2Pac - Cant C Me',
                 '2Pac - Changes',
                 '2Pac - Picture Me Rollin',
                 '2Pac - Wonda why they call u B']
list_of_songs = ['musique/Axelle Red - Ce matin.mp3',
                 'musique/Axelle Red - Ma prière.mp3',
                 'musique/BENEE - Supalonely ft. Gus Dapperton.mp3',
                 'musique/Clara Luciani - Nue.mp3',
                 'musique/The Prince Karma - Later Bitches.mp3',
                 'musique/2Pac&Biggie - Redbone.mp3',
                 'musique/2Pac - Cant C Me.mp3',
                 'musique/2Pac - Changes.mp3',
                 'musique/2Pac - Picture Me Rollin.mp3',
                 'musique/2Pac - Wonda why they call u B.mp3']
list_of_cover = ['image/Ce Matin.jpg',
                 'image/Ma prière.jpg',
                 'image/Supalonely.jpg',
                 'image/Nue.jpeg',
                 'image/Later bitches.jpg',
                 'image/BIG&2PAC.jpg',
                 'image/2PAC.jpg',
                 'image/Changes.jpg',
                 'image/2PAC.jpg',
                 'image/2PAC.jpg']
